--------------------------------------------------------
--  파일이 생성됨 - 금요일-9월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PR_CATEGORY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_CATEGORY" 
   (	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"CATEGORY_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_COUNTRY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_COUNTRY" 
   (	"COUNTRY_NAME" VARCHAR2(50 BYTE), 
	"COUNTRY_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_FAV
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_FAV" 
   (	"MEMBER_NUM" NUMBER, 
	"GENRE_NUM" NUMBER, 
	"GENRE_FAV" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_GENRE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_GENRE" 
   (	"GENRE_NAME" VARCHAR2(50 BYTE), 
	"GENRE_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_MEMBER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_MEMBER" 
   (	"MEMBER_NUM" NUMBER, 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"BIRTH" DATE, 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"STATUS_CODE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_SCORE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_SCORE" 
   (	"MEMBER_NUM" NUMBER, 
	"BOOK_NUM" NUMBER, 
	"SCORE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_PUBLISHER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_PUBLISHER" 
   (	"PUBLISHER_NAME" VARCHAR2(100 BYTE), 
	"PUBLISHER_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_TRANSLATED
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_TRANSLATED" 
   (	"TRANSLATED_STATUS" VARCHAR2(50 BYTE), 
	"TRANSLATED_CODE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_TYPE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_TYPE" 
   (	"TYPE_NAME" VARCHAR2(50 BYTE), 
	"TYPE_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_WORK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_WORK" 
   (	"BOOK_NUM" NUMBER, 
	"BOOK_NAME" VARCHAR2(200 BYTE), 
	"WRITER_NUM" NUMBER, 
	"PUBLISHER_NUM" NUMBER, 
	"COUNTRY_NUM" NUMBER, 
	"TRANSLATED_CODE" NUMBER(1,0), 
	"CATEGORY_NUM" NUMBER, 
	"TYPE_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_WORKTOGENRE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_WORKTOGENRE" 
   (	"BOOK_NUM" NUMBER, 
	"GENRE_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PR_WRITER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PR_WRITER" 
   (	"WRITER_NUM" NUMBER, 
	"WRITER_NAME" VARCHAR2(100 BYTE), 
	"COUNTRY_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PR_CATEGORY
SET DEFINE OFF;
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('소설',101);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('에세이',102);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('시',103);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('희곡',104);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('만화',200);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('학습/교육',300);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('문제집',310);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('초등문제집',311);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('중등문제집',312);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('고등문제집',313);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('사전/백과사전',320);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('전문/학술 서적',400);
Insert into SYSTEM.PR_CATEGORY (CATEGORY_NAME,CATEGORY_NUM) values ('실용/취미',500);
REM INSERTING into SYSTEM.PR_COUNTRY
SET DEFINE OFF;
Insert into SYSTEM.PR_COUNTRY (COUNTRY_NAME,COUNTRY_NUM) values ('국내',1);
Insert into SYSTEM.PR_COUNTRY (COUNTRY_NAME,COUNTRY_NUM) values ('일본',2);
Insert into SYSTEM.PR_COUNTRY (COUNTRY_NAME,COUNTRY_NUM) values ('중국',3);
Insert into SYSTEM.PR_COUNTRY (COUNTRY_NAME,COUNTRY_NUM) values ('영미',4);
Insert into SYSTEM.PR_COUNTRY (COUNTRY_NAME,COUNTRY_NUM) values ('기타국가',5);
REM INSERTING into SYSTEM.PR_FAV
SET DEFINE OFF;
REM INSERTING into SYSTEM.PR_GENRE
SET DEFINE OFF;
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('액션',100);
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('판타지',200);
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('로맨스',300);
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('코미디',400);
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('드라마',500);
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('스포츠',600);
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('추리',700);
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('공포',800);
Insert into SYSTEM.PR_GENRE (GENRE_NAME,GENRE_NUM) values ('SF',900);
REM INSERTING into SYSTEM.PR_MEMBER
SET DEFINE OFF;
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (1,'관리자',to_date('97/10/04','RR/MM/DD'),'01012345678','admin00@gmail.com','adminid00','adminpw00','관리자',0);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (2,'김철',to_date('86/08/28','RR/MM/DD'),'01086081873','iron28@naver.com','miae18','iron28','철왕',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (3,'김지훈',to_date('90/01/22','RR/MM/DD'),'01090112234','jihun90@gmail.com','jihun90','jihunpw22','훈지',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (4,'박소영',to_date('95/07/03','RR/MM/DD'),'01095070345','soyoung95@hanmail.net','soyoung95','pass1234','SOY',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (5,'이태현',to_date('88/11/15','RR/MM/DD'),'01088111567','taehyun88@kakao.com','taehyun88','taePass88','eKDLGYS',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (6,'최수정',to_date('92/03/09','RR/MM/DD'),'01092030989','sujeong92@naver.com','sujeong92','sujeongPW','CRYSTAL',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (7,'정유진',to_date('97/06/27','RR/MM/DD'),'01097062712','yujin97@gmail.com','yujin97','yujin!97','JYJ',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (8,'오상민',to_date('85/09/01','RR/MM/DD'),'01085090155','sangmin85@daum.net','sangmin85','sangMin85','5SANG',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (9,'한지훈',to_date('93/12/10','RR/MM/DD'),'01093121034','jihoon93@naver.com','jihoon93','jiHoon93#','KPAPER',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (10,'윤하늘',to_date('99/05/14','RR/MM/DD'),'01099051466','haneul99@outlook.com','haneul99','haneulPW99','SKY',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (11,'배민정',to_date('87/02/28','RR/MM/DD'),'01087022878','minjung87@korea.com','minjung87','minjung87PW','BOATPEAR',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (12,'최번개',to_date('97/10/04','RR/MM/DD'),'01012345678','lightning410@naver.com','thunder1004','choi1004','번개맨',9);
Insert into SYSTEM.PR_MEMBER (MEMBER_NUM,MEMBER_NAME,BIRTH,PHONE,EMAIL,ID,PASSWORD,NICKNAME,STATUS_CODE) values (13,'황미애',to_date('86/08/18','RR/MM/DD'),'01086081872','miae18@naver.com','miae18','iron28','ㅇㅅㅇ',9);
REM INSERTING into SYSTEM.PR_SCORE
SET DEFINE OFF;
REM INSERTING into SYSTEM.PR_PUBLISHER
SET DEFINE OFF;
REM INSERTING into SYSTEM.PR_TRANSLATED
SET DEFINE OFF;
Insert into SYSTEM.PR_TRANSLATED (TRANSLATED_STATUS,TRANSLATED_CODE) values ('한국어 원작',1);
Insert into SYSTEM.PR_TRANSLATED (TRANSLATED_STATUS,TRANSLATED_CODE) values ('번역본',2);
Insert into SYSTEM.PR_TRANSLATED (TRANSLATED_STATUS,TRANSLATED_CODE) values ('원서',3);
REM INSERTING into SYSTEM.PR_TYPE
SET DEFINE OFF;
Insert into SYSTEM.PR_TYPE (TYPE_NAME,TYPE_NUM) values ('책',1);
Insert into SYSTEM.PR_TYPE (TYPE_NAME,TYPE_NUM) values ('전자책',2);
Insert into SYSTEM.PR_TYPE (TYPE_NAME,TYPE_NUM) values ('웹툰',3);
Insert into SYSTEM.PR_TYPE (TYPE_NAME,TYPE_NUM) values ('웹소설',4);
REM INSERTING into SYSTEM.PR_WORK
SET DEFINE OFF;
REM INSERTING into SYSTEM.PR_WORKTOGENRE
SET DEFINE OFF;
REM INSERTING into SYSTEM.PR_WRITER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008402
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008402" ON "SYSTEM"."PR_MEMBER" ("MEMBER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_WORKTOGENRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_WORKTOGENRE" ON "SYSTEM"."PR_WORKTOGENRE" ("BOOK_NUM", "GENRE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PR_MEMBER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PR_MEMBER" ADD PRIMARY KEY ("MEMBER_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PR_WORKTOGENRE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PR_WORKTOGENRE" ADD CONSTRAINT "PK_WORKTOGENRE" PRIMARY KEY ("BOOK_NUM", "GENRE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
